In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/dataset/credit-2.csv')
df

Unnamed: 0  Unnamed: 1  Unnamed: 2  ... Unnamed: 13 Unnamed: 14 Unnamed: 15
0            b      3083.0         0.0  ...         202           0    positive
1            a      5867.0       446.0  ...          43         560    positive
2            a       245.0         5.0  ...         280         824    positive
3            b      2783.0       154.0  ...         100           3    positive
4            b      2017.0      5625.0  ...         120           0    positive
..         ...         ...         ...  ...         ...         ...         ...
648          b      2108.0     10085.0  ...         260           0    negative
649          a      2267.0        75.0  ...         200         394    negative
650          a      2525.0       135.0  ...         200           1    negative
651          b      1792.0       205.0  ...         280         750    negative
652          b        35.0      3375.0  ...           0           0    negative

[653 rows x 16 columns]

In [ ]:
def distance(a,b,c,d,e,z,f,g,h,i,j,z1):
  return math.sqrt((a-f)**2+(b-g)**2+(c-h)**2+(d-i)**2+(e-j)**2+(z-z1)**2)
df.iloc[:,1]/=100000
df.iloc[:,2]/=100000
df.iloc[:,7]/=100000
df.iloc[:,10]/=100000
df.iloc[:,13]/=100000
df.iloc[:,14]/=100000

In [ ]:
import math
import numpy as np
dist=np.array(np.zeros((653,653), dtype=float))
for i in range(653):
  for j in range(653):
    dist[i][j]=distance(df.iloc[i][1],df.iloc[i][2],df.iloc[i][7],df.iloc[i][13],df.iloc[i][14],df.iloc[i][10],df.iloc[j][1],df.iloc[j][2],df.iloc[j][7],df.iloc[j][13],df.iloc[j][14],df.iloc[i][10])
dist
    


array([[0.        , 0.02884527, 0.02958281, ..., 0.00587131, 0.01513912,
        0.04606229],
       [0.02884527, 0.        , 0.05657804, ..., 0.03419652, 0.04104385,
        0.06571327],
       [0.02958281, 0.05657804, 0.        , ..., 0.02428826, 0.01561668,
        0.03580638],
       ...,
       [0.00587131, 0.03419652, 0.02428826, ..., 0.        , 0.01053373,
        0.04173923],
       [0.01513912, 0.04104385, 0.01561668, ..., 0.01053373, 0.        ,
        0.03802299],
       [0.04606229, 0.06571327, 0.03580638, ..., 0.04173923, 0.03802299,
        0.        ]])

In [ ]:
dist1=np.exp(-1*dist)
print(dist1)

[[1.         0.97156679 0.97085047 ... 0.99414589 0.9849749  0.95498247]
 [0.97156679 1.         0.94499273 ... 0.96638157 0.95978704 0.93639932]
 [0.97085047 0.94499273 1.         ... 0.97600432 0.98450463 0.96482708]
 ...
 [0.99414589 0.96638157 0.97600432 ... 1.         0.98952156 0.95911986]
 [0.9849749  0.95978704 0.98450463 ... 0.98952156 1.         0.96269081]
 [0.95498247 0.93639932 0.96482708 ... 0.95911986 0.96269081 1.        ]]


In [ ]:
classes=set(df.iloc[:,15])
classes

{'negative', 'positive'}

In [ ]:
dist

array([[0.        , 0.02884527, 0.02958281, ..., 0.00587131, 0.01513912,
        0.04606229],
       [0.02884527, 0.        , 0.05657804, ..., 0.03419652, 0.04104385,
        0.06571327],
       [0.02958281, 0.05657804, 0.        , ..., 0.02428826, 0.01561668,
        0.03580638],
       ...,
       [0.00587131, 0.03419652, 0.02428826, ..., 0.        , 0.01053373,
        0.04173923],
       [0.01513912, 0.04104385, 0.01561668, ..., 0.01053373, 0.        ,
        0.03802299],
       [0.04606229, 0.06571327, 0.03580638, ..., 0.04173923, 0.03802299,
        0.        ]])

In [ ]:
list=[0,3,4,5,6,8,9,11,12]
similarity_index=np.array(np.zeros((653,653), dtype=float))
for j in list:  
  print(j)
  for i in range(len(df)):
    for z in range(i+1 ,len(df)):
      if(df.iloc[i][j] == df.iloc[z][j]):
        similarity_index[i][j]=1
        similarity_index[z][j]=1
similarity_index

0
3
4
5
6
8
9
11
12


array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
entropy=np.array(np.zeros((9,1), dtype=float))
val=0
bro=0
for j in list:
  category=set(df.iloc[:,j])
  cnt=0
  val=0
  for z in category:
    cnt=0
    for i in range(len(df)):
      if(df.iloc[i][j]==z):
        cnt+=1
    prob=cnt/653
    log_prob=math.log(prob)
    val+=(prob*log_prob)
  if(bro<9):
    entropy[bro]=-1*val
    bro+=1
    
  category={}
print(entropy)


[[0.6197973 ]
 [0.56257778]
 [0.56257778]
 [2.43161089]
 [1.25182575]
 [0.69077082]
 [0.68581113]
 [0.69032916]
 [0.30212991]]


In [ ]:
sum=0
for i in entropy:
  sum+=i
bro=0
for i in list:
  if(bro<9):
    similarity_index[:,i]=entropy[bro]/sum
  bro+=1
sum=np.sum(similarity_index)
sum=9/15*sum
sum

391.8

In [ ]:
#similarity matrix
dist2=6/15*dist1+sum
print(dist2)

[[392.2        392.18862671 392.18834019 ... 392.19765836 392.19398996
  392.18199299]
 [392.18862671 392.2        392.17799709 ... 392.18655263 392.18391482
  392.17455973]
 [392.18834019 392.17799709 392.2        ... 392.19040173 392.19380185
  392.18593083]
 ...
 [392.19765836 392.18655263 392.19040173 ... 392.2        392.19580862
  392.18364794]
 [392.19398996 392.18391482 392.19380185 ... 392.19580862 392.2
  392.18507633]
 [392.18199299 392.17455973 392.18593083 ... 392.18364794 392.18507633
  392.2       ]]


In [ ]:
def hierarchical_clustering(dist,linkage,no_of_clusters):  
    #first step is to calculate the initial distance matrix
    #it consists distances from all the point to all the point
    color = ['r','g','b','y','c','m','k','w']
    # initial_distances = pairwise_distances(data,metric='euclidean')
    #making all the diagonal elements infinity 
    np.fill_diagonal(dist,sys.maxsize)
    clusters = find_clusters(dist,linkage)
    
    #plotting the clusters
    iteration_number = dist.shape[0] - no_of_clusters
    clusters_to_plot = clusters[iteration_number]
    # arr = np.unique(clusters_to_plot)
    
    # indices_to_plot = []
    # fig = plt.figure()
    # fig.suptitle('Scatter Plot for clusters')
    # ax = fig.add_subplot(1,1,1)
    # ax.set_xlabel('X')
    # ax.set_ylabel('Y')
    # for x in np.nditer(arr):
    #     indices_to_plot.append(np.where(clusters_to_plot==x))
    # p=0
    
    
    print(clusters_to_plot)
    # for i in range(0,len(indices_to_plot)):
    #     for j in np.nditer(indices_to_plot[i]):
    #            ax.scatter(df.iloc[j,0],df.[j,1], c= color[p])
    #     p = p + 1
        
    # plt.show()

In [ ]:
def find_clusters(input,linkage):
    clusters = {}
    row_index = -1
    col_index = -1
    array = []
    

    for n in range(input.shape[0]):
        array.append(n)
        
    clusters[0] = array.copy()

    #finding minimum value from the distance matrix
    #note that this loop will always return minimum value from bottom triangle of matrix
    for k in range(1, input.shape[0]):
        min_val = sys.maxsize
  
        for i in range(0, input.shape[0]):
            for j in range(0, input.shape[1]):
                if(input[i][j]<=min_val):
                    min_val = input[i][j]
                    row_index = i
                    col_index = j
        
        #once we find the minimum value, we need to update the distance matrix
        #updating the matrix by calculating the new distances from the cluster to all points
        
        #for Single Linkage
        if(linkage == "single" or linkage =="Single"):
            for i in range(0,input.shape[0]):
                if(i != col_index):
                    #we calculate the distance of every data point from newly formed cluster and update the matrix.
                    temp = min(input[col_index][i],input[row_index][i])
                    #we update the matrix symmetrically as our distance matrix should always be symmetric
                    input[col_index][i] = temp
                    input[i][col_index] = temp
        #for Complete Linkage
        elif(linkage=="Complete" or linkage == "complete"):
             for i in range(0,input.shape[0]):
                if(i != col_index and i!=row_index):
                    temp = min(input[col_index][i],input[row_index][i])
                    input[col_index][i] = temp
                    input[i][col_index] = temp
        #for Average Linkage
        elif(linkage=="Average" or linkage == "average"):
             for i in range(0,input.shape[0]):
                if(i != col_index and i!=row_index):
                    temp = (input[col_index][i]+input[row_index][i])/2
                    input[col_index][i] = temp
                    input[i][col_index] = temp
        
        elif(linkage=="Centroid" or linkage =="centroid"):
            for i in range(0,input.shape[0]):
                if(i!=col_index and i!=row_index):
                    dist_centroid = cal_dist_from_centroid(i,row_index,col_index)
                    input[col_index][i] = dist_centroid
                    input[i][col_index] = dist_centroid
                   
        #set the rows and columns for the cluster with higher index i.e. the row index to infinity
        #Set input[row_index][for_all_i] = infinity
        #set input[for_all_i][row_index] = infinity
        for i in range (0,input.shape[0]):
            input[row_index][i] = sys.maxsize
            input[i][row_index] = sys.maxsize
            
        #Manipulating the dictionary to keep track of cluster formation in each step
        #if k=0,then all datapoints are clusters
       
        minimum = min(row_index,col_index)
        maximum = max(row_index,col_index)
        for n in range(len(array)):
            if(array[n]==maximum):
                array[n] = minimum
        clusters[k] = array.copy()
           
    return clusters

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances
import sys
dist3=np.log(1/dist2)

In [ ]:
hierarchical_clustering(dist4,"single",2)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
dist4=-1*dist3
# dist4*=10**8
dist4

array([[5.97177191, 5.97174291, 5.97174218, ..., 5.97176594, 5.97175659,
        5.971726  ],
       [5.97174291, 5.97177191, 5.97171581, ..., 5.97173763, 5.9717309 ,
        5.97170705],
       [5.97174218, 5.97171581, 5.97177191, ..., 5.97174744, 5.97175611,
        5.97173604],
       ...,
       [5.97176594, 5.97173763, 5.97174744, ..., 5.97177191, 5.97176123,
        5.97173022],
       [5.97175659, 5.9717309 , 5.97175611, ..., 5.97176123, 5.97177191,
        5.97173386],
       [5.971726  , 5.97170705, 5.97173604, ..., 5.97173022, 5.97173386,
        5.97177191]])