In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/dataset/breast.csv')
df=df[:500]

In [ ]:
import numpy as np 
import math
entropy=np.array(np.zeros((9,1), dtype=float))
val=0
bro=0
for j in range(0,9):
  category=set(df.iloc[:,j])
  cnt=0
  val=0
  print(category)
  for z in category:
    cnt=0
    for i in range(277):
      if(df.iloc[i][j]==z):
        cnt+=1
    prob=cnt/277
    log_prob=math.log(prob)
    val+=(prob*log_prob)
  if(bro<9):
    entropy[bro]=-1*val
    bro+=1
    
  category={}
print(entropy)
# ordinal = [0,2,3,5]
# nominal = [1,4,6,7,8]

{'40-49', '70-79', '60-69', '20-29', '50-59', '30-39'}
{'premeno', 'ge40', 'lt40'}
{'5-9', '0-4', '45-49', '40-44', '35-39', '15-19', '25-29', '20-24', '50-54', '10-14', '30-34'}
{'15-17', '3-5', '9-11', '6-8', '12-14', '0-2', '24-26'}
{'yes', 'no'}
{1, 2, 3}
{'left', 'right'}
{'central', 'right_low', 'left_up', 'right_up', 'left_low'}
{'yes', 'no'}
[[1.40945415]
 [0.76649453]
 [2.10846755]
 [0.88655719]
 [0.5033906 ]
 [1.05801032]
 [0.6920455 ]
 [1.38997295]
 [0.53170881]]


In [ ]:
classes=set(df.iloc[:,9])
classes

{'no-recurrence-events', 'recurrence-events'}

In [ ]:
weight=np.array(np.zeros((9,1),dtype=float))
for i in range(9):
  weight[i]=entropy[i]/np.sum(entropy)
weight

array([[0.15080664],
       [0.08201222],
       [0.22559861],
       [0.0948585 ],
       [0.05386102],
       [0.11320338],
       [0.07404643],
       [0.14872222],
       [0.05689097]])

In [ ]:
#distance matrix will be of the form attribute * attribute (6*6) in this case :
#applying algorithm : 
ordinal=[0,2,3,5]
nominal=[1,4,6,7,8]
distance_mat=np.array(np.zeros((9,9),dtype=float))
v_mat=np.array(np.zeros((9,9),dtype=float))
for i in ordinal :
  for j in range(9):
      start=min(i,j)
      end=max(i,j)
      sum=0
      for i in range(start,end):
        if(i in ordinal):
          sum+=entropy[i]
      if(j in ordinal and i != j):
        v_mat[j][i]=weight[i]*sum
#nominal which is not in order so will be directly adding the sum thing here in this .
for i in nominal :
  for j in range(9):
    start=min(i,j)
    end=max(i,j)
    sum=0
    if(j in nominal and i != j):
      v_mat[j][i]=weight[i]*(entropy[start]+entropy[end])
v_mat


array([[0.        , 0.11559246, 0.79363826, 0.        , 0.23722974,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.06839731,
        0.        , 0.10799969, 0.32071463, 0.07385605],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.47566735, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.1041461 , 0.        , 0.        , 0.        ,
        0.        , 0.08851778, 0.28158523, 0.05888781],
       [0.        , 0.        , 0.        , 0.        , 0.04775088,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.1196181 , 0.        , 0.        , 0.06438741,
        0.        , 0.        , 0.3096424 , 0.06962057],
       [0.        , 0.17685668, 0.        , 0.        , 0.1019785 ,
        0.        , 0.15416604, 0.        , 0.10932635],


In [ ]:
def distance(a,b):
  sum=0
  for i in range(9):
    sum+=((a[i]-b[i])**2)
  return math.sqrt(sum)

In [ ]:
#now will be calculating distance matrix : 
for i in range(9):
  for j in range(9):
    distance_mat[i][j]=distance(v_mat[i],v_mat[j])
distance_mat


array([[0.        , 0.88977762, 0.83636191, 0.4132131 , 0.88139892,
        0.82409073, 0.87205378, 0.82923296, 0.86762324],
       [0.88977762, 0.        , 0.35306474, 0.59238007, 0.13288832,
        0.34699106, 0.16164478, 0.37236182, 0.13591055],
       [0.83636191, 0.35306474, 0.        , 0.47566735, 0.31849619,
        0.04775088, 0.34522409, 0.27820374, 0.32300865],
       [0.4132131 , 0.59238007, 0.47566735, 0.        , 0.57245022,
        0.47805813, 0.58774068, 0.55105059, 0.57497306],
       [0.88139892, 0.13288832, 0.31849619, 0.57245022, 0.        ,
        0.32205585, 0.1145553 , 0.3191088 , 0.08126213],
       [0.82409073, 0.34699106, 0.04775088, 0.47805813, 0.32205585,
        0.        , 0.3395743 , 0.26445858, 0.31826148],
       [0.87205378, 0.16164478, 0.34522409, 0.58774068, 0.1145553 ,
        0.3395743 , 0.        , 0.35484007, 0.11778855],
       [0.82923296, 0.37236182, 0.27820374, 0.55105059, 0.3191088 ,
        0.26445858, 0.35484007, 0.        , 0.32366997],


NOW APPLYING K-MODE ALGORITHM ON IT
* NUMBER OF CLUSTERS WILL BE : TWO [2]

In [ ]:
def belongs(mode1,mode2):
  belongsto=np.array(np.zeros((277,2)),dtype=int)
  for i in range(277):
    #for cluster1 : 
    cnt=0
    if(df[i][0]!=mode1[0]):
      cnt+=1
    if(df[i][1]!=mode1[1]):
      cnt+=1
    if(df[i][2]!=mode1[2]):
      cnt+=1
    if(df[i][3]!=mode1[3]):
      cnt+=1
    if(df[i][4]!=mode1[4]):
      cnt+=1
    if(df[i][5]!=mode1[5]):
      cnt+=1
    if(df[i][6]!=mode1[6]):
      cnt+=1
    if(df[i][7]!=mode1[7]):
      cnt+=1
    if(df[i][8]!=mode1[8]):
      cnt+=1
    if(df[i][9]!=mode1[9]):
      cnt+=1
    belongsto[i][0]=cnt

    #for cluster 2
    cnt=0
    if(df[i][0]!=mode1[0]):
      cnt+=1
    if(df[i][1]!=mode1[1]):
      cnt+=1
    if(df[i][2]!=mode1[2]):
      cnt+=1
    if(df[i][3]!=mode1[3]):
      cnt+=1
    if(df[i][4]!=mode1[4]):
      cnt+=1
    if(df[i][5]!=mode1[5]):
      cnt+=1
    if(df[i][6]!=mode1[6]):
      cnt+=1
    if(df[i][7]!=mode1[7]):
      cnt+=1
    if(df[i][8]!=mode1[8]):
      cnt+=1
    if(df[i][9]!=mode1[9]):
      cnt+=1
    belongsto[i][0]=cnt
    cnt=0

#now finding the cluster in which the particular point belongs to and this functon will return that list only : 
  cluster=np.array(np.zeros((277,1)),dtype=int)
  min=10000
  pos=0
  for i in range(277):
   min=10000
   for j in range(2):
      if(min>belongsto[i][j]):
        min=belongsto[i][j]
        # print(min)
        pos=j
      
   cluster[i]=pos
   # print(pos)
#now we will be finding for the points that belongs to each cluster and will return that from this function : 
  #finding points that belong to each cluster till now:
  cluster1=[]
  cluster2=[]
  for i in range(277):
    if(cluster[i]==0):
      cluster1.append(i)
    if(cluster[i]==1):
      cluster2.append(i)
  return cluster1,cluster2

In [ ]:
def mode(cluster1,cluster2) :
  clus11={'40-49':0, '70-79':0, '60-69':0, '20-29':0, '50-59':0, '30-39':0}
  clus12={'premeno', 'ge40', 'lt40'}
  clus13={'5-9':0, '0-4':0, '45-49':0, '40-44':0, '35-39':0, '15-19':0, '25-29':0, '20-24':0, '50-54':0, '10-14':0, '30-34':0}
  clus14={'15-17':0, '3-5':0, '9-11':0, '6-8':0, '12-14':0, '0-2':0, '24-26':0}
  clus15={'yes':0, 'no':0}
  clus16={1:0, 2:0, 3:0}
  clus17={'left':0, 'right':0}
  clus18={'central':0, 'right_low':0, 'left_up':0, 'right_up':0, 'left_low':0}
  clus19={'yes':0, 'no':0}
  for i in cluster1:
    x=df[i][0:9]
  # print(x)
    clus11[x[0]]+=1
    clus12[x[1]]+=1
    clus13[x[2]]+=1
    clus14[x[3]]+=1
    clus15[x[4]]+=1
    clus16[x[5]]+=1
    clus17[x[6]]+=1
    clus18[x[7]]+=1
    clus19[x[8]]+=1
  keymax1 = max(clus11, key=clus11.get)
  keymax2 = max(clus12, key=clus12.get)
  keymax3 = max(clus13, key=clus13.get)
  keymax4 = max(clus14, key=clus14.get)
  keymax5 = max(clus15, key=clus15.get)
  keymax6 = max(clus16, key=clus16.get)
  keymax7 = max(clus17, key=clus17.get)
  keymax8 = max(clus18, key=clus18.get)
  keymax9 = max(clus19, key=clus19.get)
  #mode for cluster1

  mode1=np.array([keymax1,keymax2,keymax3,keymax4,keymax5,keymax6,keymax7,keymax8,keymax9])
  clus11={'40-49':0, '70-79':0, '60-69':0, '20-29':0, '50-59':0, '30-39':0}
  clus12={'premeno', 'ge40', 'lt40'}
  clus13={'5-9':0, '0-4':0, '45-49':0, '40-44':0, '35-39':0, '15-19':0, '25-29':0, '20-24':0, '50-54':0, '10-14':0, '30-34':0}
  clus14={'15-17':0, '3-5':0, '9-11':0, '6-8':0, '12-14':0, '0-2':0, '24-26':0}
  clus15={'yes':0, 'no':0}
  clus16={1:0, 2:0, 3:0}
  clus17={'left':0, 'right':0}
  clus18={'central':0, 'right_low':0, 'left_up':0, 'right_up':0, 'left_low':0}
  clus19={'yes':0, 'no':0}
  #mode for cluster2

  for i in cluster2:
    x=df[i][0:9]
  # print(x)
    clus11[x[0]]+=1
    clus12[x[1]]+=1
    clus13[x[2]]+=1
    clus14[x[3]]+=1
    clus15[x[4]]+=1
    clus16[x[5]]+=1
    clus17[x[6]]+=1
    clus18[x[7]]+=1
    clus19[x[8]]+=1
  keymax1 = max(clus11, key=clus11.get)
  keymax2 = max(clus12, key=clus12.get)
  keymax3 = max(clus13, key=clus13.get)
  keymax4 = max(clus14, key=clus14.get)
  keymax5 = max(clus15, key=clus15.get)
  keymax6 = max(clus16, key=clus16.get)
  keymax7 = max(clus17, key=clus17.get)
  keymax8 = max(clus18, key=clus18.get)
  keymax9 = max(clus19, key=clus19.get)
  mode2=np.array([keymax1,keymax2,keymax3,keymax4,keymax5,keymax6,keymax7,keymax8,keymax9])

In [ ]:
#main algorithm for kmode : 
cluster1_new=[]
cluster2_new=[]
cluster3_new=[]
cluster4_new=[]
while(cluster1!=cluster1_new and cluster2!=cluster2_new and cluster3!=cluster3_new and cluster4!=cluster4_new):
  cluster1_new,cluster2_new,cluster3_new,cluster4_new = belongs(mode1,mode2,mode3,mode4)

In [ ]:
#finds four random numbers between 0 and 277
import random
def Rand(start, end, num): 
    res = [] 
  
    for j in range(num): 
        res.append(random.randint(start, end)) 
  
    return res 
print(Rand(0, 277, 2)) 
rand_no=Rand(0,277,2)

[91, 222]


In [ ]:
import numpy as np
belongsto=np.array(np.zeros((277,2)),dtype=int)
df=np.array(df)

In [ ]:
for i in range(277):
  cnt=0
  for j in range(2):
    if(df[i][0]!=df[rand_no[j]][0]):
      cnt+=1
    if(df[i][1]!=df[rand_no[j]][1]):
      cnt+=1
    if(df[i][2]!=df[rand_no[j]][2]):
      cnt+=1
    if(df[i][3]!=df[rand_no[j]][3]):
      cnt+=1
    if(df[i][4]!=df[rand_no[j]][4]):
      cnt+=1
    if(df[i][5]!=df[rand_no[j]][5]):
      cnt+=1
    if(df[i][6]!=df[rand_no[j]][6]):
      cnt+=1
    if(df[i][7]!=df[rand_no[j]][7]):
      cnt+=1
    if(df[i][8]!=df[rand_no[j]][8]):
      cnt+=1
    if(df[i][9]!=df[rand_no[j]][9]):
      cnt+=1
    belongsto[i][j]=cnt
    cnt=0

In [ ]:
cluster=np.array(np.zeros((277,1)),dtype=int)
min=10000
pos=0
for i in range(277):
  min=10000
  for j in range(4):
    if(min>belongsto[i][j]):
      min=belongsto[i][j]
      # print(min)
      pos=j
      
  cluster[i]=pos
  # print(pos)
  #finding points that belong to each cluster till now:
cluster1=[]
cluster2=[]
for i in range(277):
  if(cluster[i]==0):
    cluster1.append(i)
  if(cluster[i]==1):
    cluster2.append(i)