In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/dataset/nursery.csv')
df=df[:500]
import random 
df

Unnamed: 0 Unnamed: 1  ...    Unnamed: 7  Unnamed: 8
0        usual     proper  ...   recommended   recommend
1        usual     proper  ...     not_recom   not_recom
2        usual     proper  ...      priority    priority
3        usual     proper  ...   recommended    priority
4        usual     proper  ...      priority    priority
..         ...        ...  ...           ...         ...
495      usual     proper  ...      priority    priority
496      usual     proper  ...     not_recom   not_recom
497      usual     proper  ...   recommended    priority
498      usual     proper  ...      priority    priority
499      usual     proper  ...     not_recom   not_recom

[500 rows x 9 columns]

In [ ]:
import numpy as np 
import math
entropy=np.array(np.zeros((8,1), dtype=float))
val=0
bro=0
for j in range(0,8):
  category=set(df.iloc[:,j])
  cnt=0
  val=0
  print(category)
  for z in category:
    cnt=0
    for i in range(500):
      if(df.iloc[i][j]==z):
        cnt+=1
    prob=cnt/500
    log_prob=math.log(prob)
    val+=(prob*log_prob)
  if(bro<8):
    entropy[bro]=-1*val
    bro+=1
    
  category={}
print(entropy)

#ordinal = 4 , 5 ,7
#nominal = 2,3,6

{'usual'}
{' proper'}
{' completed', ' complete', ' incomplete'}
{'3', '1', '2', ' more'}
{' convenient', ' critical', ' less_conv'}
{' convenient', ' inconv'}
{' nonprob', ' problematic', ' slightly_prob'}
{' recommended', ' priority', ' not_recom'}
[[-0.        ]
 [-0.        ]
 [ 1.0663421 ]
 [ 1.37077737]
 [ 1.09750906]
 [ 0.69313918]
 [ 1.09819778]
 [ 1.09841665]]


In [ ]:
reliability=entropy[2:]
reliability

array([[1.0663421 ],
       [1.37077737],
       [1.09750906],
       [0.69313918],
       [1.09819778],
       [1.09841665]])

In [ ]:
weight=np.array(np.zeros((6,1),dtype=float))
for i in range(6):
  weight[i]=reliability[i]/np.sum(reliability)
weight

array([[0.1659836 ],
       [0.21337108],
       [0.17083496],
       [0.10789196],
       [0.17094216],
       [0.17097623]])

In [ ]:
classes=set(df.iloc[:,8])
classes

{' not_recom', ' priority', ' recommend', ' very_recom'}

In [ ]:
#distance matrix will be of the form attribute * attribute (6*6) in this case :
#applying algorithm : 
ordinal=[2,3,5]
nominal=[0,1,4]
distance_mat=np.array(np.zeros((6,6),dtype=float))
v_mat=np.array(np.zeros((6,6),dtype=float))
for i in ordinal :
  for j in range(6):
      start=min(i,j)
      end=max(i,j)
      sum=0
      for i in range(start,end):
        if(i in ordinal):
          sum+=reliability[i]
      if(j in ordinal and i != j):
        v_mat[j][i]=weight[i]*sum
#nominal which is not in order so will be directly adding the sum thing here in this .
for i in nominal :
  for j in range(6):
    start=min(i,j)
    end=max(i,j)
    sum=0
    if(j in nominal and i != j):
      v_mat[j][i]=weight[i]*(reliability[start]+reliability[end])
v_mat


array([[0.        , 0.52001082, 0.        , 0.        , 0.37001113,
        0.        ],
       [0.40452187, 0.        , 0.        , 0.        , 0.42205195,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.18749291, 0.        , 0.        ,
        0.        ],
       [0.35927813, 0.5268079 , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.11848671,
        0.        ]])

In [ ]:
def distance(a,b):
  sum=0
  for i in range(6):
    sum+=((a[i]-b[i])**2)
  return math.sqrt(sum)

In [ ]:
#now will be calculating distance matrix : 
for i in range(6):
  for j in range(6):
    distance_mat[i][j]=distance(v_mat[i],v_mat[j])
distance_mat


array([[0.        , 0.66087627, 0.63821586, 0.6651865 , 0.51578601,
        0.57764676],
       [0.66087627, 0.        , 0.58460739, 0.61393761, 0.67653633,
        0.50575666],
       [0.63821586, 0.58460739, 0.        , 0.18749291, 0.63765769,
        0.11848671],
       [0.6651865 , 0.61393761, 0.18749291, 0.        , 0.66465098,
        0.22179426],
       [0.51578601, 0.67653633, 0.63765769, 0.66465098, 0.        ,
        0.64857261],
       [0.57764676, 0.50575666, 0.11848671, 0.22179426, 0.64857261,
        0.        ]])

In [ ]:
len(df)

500

In [ ]:
def Rand(start, end, num): 
    res = [] 
  
    for j in range(num): 
        res.append(random.randint(start, end)) 
  
    return res 

In [ ]:
#finds four random numbers between 0 and 500
print(Rand(0, 500, 4)) 
rand_no=Rand(0,500,4)

[427, 298, 78, 296]


In [ ]:
import numpy as np
belongsto=np.array(np.zeros((500,4)),dtype=int)
#2,3,4,5,6 - categorical attribute

In [ ]:
df=np.array(df)

In [ ]:
for i in range(500):
  cnt=0
  for j in range(4):
    if(df[i][2]!=df[rand_no[j]][2]):
      cnt+=1
    if(df[i][3]!=df[rand_no[j]][3]):
      cnt+=1
    if(df[i][4]!=df[rand_no[j]][4]):
      cnt+=1
    if(df[i][5]!=df[rand_no[j]][5]):
      cnt+=1
    if(df[i][6]!=df[rand_no[j]][6]):
      cnt+=1
    belongsto[i][j]=cnt
    cnt=0

In [ ]:
def belongs(mode1,mode2,mode3,mode4):
  belongsto=np.array(np.zeros((500,4)),dtype=int)
  for i in range(500):
    cnt=0
    if(df[i][2]!=mode1[0]):
      cnt+=1
    if(df[i][3]!=mode1[1]):
      cnt+=1
    if(df[i][4]!=mode1[2]):
      cnt+=1
    if(df[i][5]!=mode1[3]):
      cnt+=1
    if(df[i][6]!=mode1[4]):
      cnt+=1
    belongsto[i][0]=cnt
    cnt=0
    if(df[i][2]!=mode2[0]):
      cnt+=1
    if(df[i][3]!=mode2[1]):
      cnt+=1
    if(df[i][4]!=mode2[2]):
      cnt+=1
    if(df[i][5]!=mode2[3]):
      cnt+=1
    if(df[i][6]!=mode2[4]):
      cnt+=1
    belongsto[i][1]=cnt
    cnt=0
    if(df[i][2]!=mode3[0]):
      cnt+=1
    if(df[i][3]!=mode3[1]):
      cnt+=1
    if(df[i][4]!=mode3[2]):
      cnt+=1
    if(df[i][5]!=mode3[3]):
      cnt+=1
    if(df[i][6]!=mode3[4]):
      cnt+=1
    belongsto[i][2]=cnt
    cnt=0
    if(df[i][2]!=mode4[0]):
      cnt+=1
    if(df[i][3]!=mode4[1]):
      cnt+=1
    if(df[i][4]!=mode4[2]):
      cnt+=1
    if(df[i][5]!=mode4[3]):
      cnt+=1
    if(df[i][6]!=mode4[4]):
      cnt+=1
    belongsto[i][3]=cnt
    cnt=0

#now finding the cluster in which the particular point belongs to and this functon will return that list only : 
  cluster=np.array(np.zeros((500,1)),dtype=int)
  min=10000
  pos=0
  for i in range(500):
   min=10000
   for j in range(4):
      if(min>belongsto[i][j]):
        min=belongsto[i][j]
        # print(min)
        pos=j
      
   cluster[i]=pos
   # print(pos)
#now we will be finding for the points that belongs to each cluster and will return that from this function : 
  #finding points that belong to each cluster till now:
  cluster1=[]
  cluster2=[]
  cluster3=[]
  cluster4=[]
  for i in range(500):
    if(cluster[i]==0):
      cluster1.append(i)
    if(cluster[i]==1):
      cluster2.append(i)
    if(cluster[i]==2):
      cluster3.append(i)
    if(cluster[i]==3):
      cluster4.append(i)
  return cluster1,cluster2,cluster3,cluster4

In [ ]:
belongsto[:15]

array([[1, 2, 3, 2],
       [1, 2, 3, 2],
       [2, 2, 3, 2],
       [2, 1, 2, 1],
       [2, 1, 2, 1],
       [2, 1, 2, 1],
       [0, 3, 4, 3],
       [0, 3, 4, 3],
       [0, 3, 4, 3],
       [1, 3, 4, 3],
       [1, 3, 4, 3],
       [1, 3, 4, 3],
       [1, 2, 3, 2],
       [1, 2, 3, 2],
       [2, 3, 4, 1]])

In [ ]:
cluster=np.array(np.zeros((500,1)),dtype=int)


In [ ]:
min=10000
pos=0
for i in range(500):
  min=10000
  for j in range(4):
    if(min>belongsto[i][j]):
      min=belongsto[i][j]
      # print(min)
      pos=j
      
  cluster[i]=pos
  # print(pos)

In [ ]:
cluster[:15]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [3]])

In [ ]:
#finding points that belong to each cluster till now:
cluster1=[]
cluster2=[]
cluster3=[]
cluster4=[]
for i in range(500):
  if(cluster[i]==0):
    cluster1.append(i)
  if(cluster[i]==1):
    cluster2.append(i)
  if(cluster[i]==2):
    cluster3.append(i)
  if(cluster[i]==3):
    cluster4.append(i)

In [ ]:
cluster2

[3,
 4,
 5,
 50,
 51,
 99,
 100,
 101,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 342,
 343,
 393,
 394,
 395,
 396,
 397,
 398,
 427,
 428,
 429,
 430,
 431,
 443,
 444,
 445,
 446,
 447,
 448,
 474,
 475,
 476,
 477,
 478,
 479,
 491,
 492,
 493,
 494,
 495,
 496]

In [ ]:
#finding modes or most common values :
def mode(cluster1,cluster2,cluster3,cluster4) :
  clus12={' completed':0, ' complete':0, ' incomplete':0}
  clus13={'3':0, '1':0, '2':0, ' more':0}
  clus14={' convenient':0, ' critical':0, ' less_conv':0}
  clus15={' convenient':0, ' inconv':0}
  clus16={' nonprob':0,' problematic':0,' slightly_prob':0}
  for i in cluster1:
    x=df[i][2:7]
  # print(x)
    clus12[x[0]]+=1
    clus13[x[1]]+=1
    clus14[x[2]]+=1
    clus15[x[3]]+=1
    clus16[x[4]]+=1
  keymax1 = max(clus12, key=clus12.get)
  keymax2 = max(clus13, key=clus13.get)
  keymax3 = max(clus14, key=clus14.get)
  keymax4 = max(clus15, key=clus15.get)
  keymax5 = max(clus16, key=clus16.get)
  #mode for cluster1

  mode1=np.array([keymax1,keymax2,keymax3,keymax4,keymax5])
  clus12={' completed':0, ' complete':0, ' incomplete':0}
  clus13={'3':0, '1':0, '2':0, ' more':0}
  clus14={' convenient':0, ' critical':0, ' less_conv':0}
  clus15={' convenient':0, ' inconv':0}
  clus16={' nonprob':0,' problematic':0,' slightly_prob':0}
  #mode for cluster2

  for i in cluster2:
    x=df[i][2:7]
  # print(x)
    clus12[x[0]]+=1
    clus13[x[1]]+=1
    clus14[x[2]]+=1
    clus15[x[3]]+=1
    clus16[x[4]]+=1
  keymax1 = max(clus12, key=clus12.get)
  keymax2 = max(clus13, key=clus13.get)
  keymax3 = max(clus14, key=clus14.get)
  keymax4 = max(clus15, key=clus15.get)
  keymax5 = max(clus16, key=clus16.get)
  mode2=np.array([keymax1,keymax2,keymax3,keymax4,keymax5])
  clus12={' completed':0, ' complete':0, ' incomplete':0}
  clus13={'3':0, '1':0, '2':0, ' more':0}
  clus14={' convenient':0, ' critical':0, ' less_conv':0}
  clus15={' convenient':0, ' inconv':0}
  clus16={' nonprob':0,' problematic':0,' slightly_prob':0}
  #mode for cluster3

  for i in cluster3:
    x=df[i][2:7]
  # print(x)
    clus12[x[0]]+=1
    clus13[x[1]]+=1
    clus14[x[2]]+=1
    clus15[x[3]]+=1
    clus16[x[4]]+=1
  keymax1 = max(clus12, key=clus12.get)
  keymax2 = max(clus13, key=clus13.get)
  keymax3 = max(clus14, key=clus14.get)
  keymax4 = max(clus15, key=clus15.get)
  keymax5 = max(clus16, key=clus16.get)
  mode3=np.array([keymax1,keymax2,keymax3,keymax4,keymax5])
  clus12={' completed':0, ' complete':0, ' incomplete':0}
  clus13={'3':0, '1':0, '2':0, ' more':0}
  clus14={' convenient':0, ' critical':0, ' less_conv':0}
  clus15={' convenient':0, ' inconv':0}
  clus16={' nonprob':0,' problematic':0,' slightly_prob':0}
  for i in cluster4:
    x=df[i][2:7]
  # print(x)
    clus12[x[0]]+=1
    clus13[x[1]]+=1
    clus14[x[2]]+=1
    clus15[x[3]]+=1
    clus16[x[4]]+=1
  keymax1 = max(clus12, key=clus12.get)
  keymax2 = max(clus13, key=clus13.get)
  keymax3 = max(clus14, key=clus14.get)
  keymax4 = max(clus15, key=clus15.get)
  keymax5 = max(clus16, key=clus16.get)
  mode4=np.array([keymax1,keymax2,keymax3,keymax4,keymax5])
  return mode1,mode2,mode3,mode4
  

In [ ]:
mode1,mode2,mode3,mode4=mode(cluster1,cluster2,cluster3,cluster4)

In [ ]:
#main algorithm for kmode : 
cluster1_new=[]
cluster2_new=[]
cluster3_new=[]
cluster4_new=[]
while(cluster1!=cluster1_new and cluster2!=cluster2_new and cluster3!=cluster3_new and cluster4!=cluster4_new):
  cluster1_new,cluster2_new,cluster3_new,cluster4_new = belongs(mode1,mode2,mode3,mode4)

In [ ]:
#displaying first 10 values from each cluster : 
print('cluster1 : ', cluster1_new[:10])
print('cluster2 : ', cluster2_new[:10])
print('cluster3 : ', cluster3_new[:10])
print('cluster4 : ', cluster4_new[:10])

cluster1 :  [0, 1, 2, 6, 7, 8, 9, 10, 11, 12]
cluster2 :  [3, 4, 5, 50, 51, 99, 100, 101, 193, 194]
cluster3 :  [147, 148, 149, 150, 151, 152, 178, 179, 180, 181]
cluster4 :  [14, 15, 16, 17, 18, 19, 20, 25, 29, 30]
